version = 0.1
[default.deploy.parameters]
stack_name = "thingpress-espressif-test"
resolve_s3 = true
s3_prefix = "thingpress-espressif-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TestId=\"test-run-1\""
