name: Deploy Thingpress

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required to checkout the repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: us-east-1  # Change to your preferred region
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ThingpressDeploymentRole
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Deploy with SAM
        run: |
          sam build
          sam deploy --stack-name thingpress \
            --parameter-overrides \
              IamUserArn=${{ secrets.IAM_USER_ARN }} \
              IoTPolicy=${{ secrets.IOT_POLICY }} \
              IoTThingGroup=${{ secrets.IOT_THING_GROUP }} \
              IoTThingType=${{ secrets.IOT_THING_TYPE }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
