name: Thingpress Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: 3.13
            - name: 'Install dependencies'
              run: pip install -r ./requirements.txt

            - name: Setup AWS SAM
              uses: aws-actions/setup-sam@819220f63fb333a9a394dd0a5cab2d8303fd17e2

            - name: Validate template
              run: sam validate --lint

            - name: Run sam build
              run: sam build --parallel
